-- MySQL Script generated by MySQL Workbench
-- Wed Feb 26 14:25:28 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema barcelona_activa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema barcelona_activa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `barcelona_activa` DEFAULT CHARACTER SET utf8 ;
USE `barcelona_activa` ;

-- -----------------------------------------------------
-- Table `barcelona_activa`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barcelona_activa`.`Address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `carrer` VARCHAR(75) NULL,
  `numero` INT NULL,
  `pis` INT NULL,
  `porta` INT NULL,
  `ciutat` VARCHAR(50) NULL,
  `codi_postal` INT NOT NULL,
  `pais` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barcelona_activa`.`Proveidors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barcelona_activa`.`Proveidors` (
  `NIF` INT NOT NULL,
  `nom` VARCHAR(100) NOT NULL,
  `telefon` INT NULL,
  `fax` INT NULL,
  `Address_id` INT NOT NULL,
  PRIMARY KEY (`NIF`),
  INDEX `fk_Proveidors_Address1_idx` (`Address_id` ASC),
  CONSTRAINT `fk_Proveidors_Address1`
    FOREIGN KEY (`Address_id`)
    REFERENCES `barcelona_activa`.`Address` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barcelona_activa`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barcelona_activa`.`Marca` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(150) NOT NULL,
  `Proveidors_NIF` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Marca_Proveidors1_idx` (`Proveidors_NIF` ASC),
  CONSTRAINT `fk_Marca_Proveidors1`
    FOREIGN KEY (`Proveidors_NIF`)
    REFERENCES `barcelona_activa`.`Proveidors` (`NIF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barcelona_activa`.`Ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barcelona_activa`.`Ulleres` (
  `codi_id` INT NOT NULL AUTO_INCREMENT,
  `graduacio_ull_esq` DECIMAL NULL,
  `graduacio_ull_dre` DECIMAL NULL,
  `tipus_muntura` VARCHAR(1) NULL COMMENT 'F=flotant\nP=pasta\nM=metalica',
  `color_muntura` VARCHAR(50) NULL,
  `color_vidre_esq` VARCHAR(50) NULL,
  `color_vidre_dre` VARCHAR(50) NULL,
  `preu` INT NULL,
  `Marca_id` INT NOT NULL,
  PRIMARY KEY (`codi_id`),
  INDEX `fk_Ulleres_Marca1_idx` (`Marca_id` ASC),
  CONSTRAINT `fk_Ulleres_Marca1`
    FOREIGN KEY (`Marca_id`)
    REFERENCES `barcelona_activa`.`Marca` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barcelona_activa`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barcelona_activa`.`Clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  `telefon` INT NOT NULL,
  `correu_electronic` VARCHAR(255) NULL,
  `data_registre` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Address_id` INT NOT NULL,
  `Clients_id_recomanat_per` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Clients_Address_idx` (`Address_id` ASC),
  INDEX `fk_Clients_Clients1_idx` (`Clients_id_recomanat_per` ASC),
  CONSTRAINT `fk_Clients_Address`
    FOREIGN KEY (`Address_id`)
    REFERENCES `barcelona_activa`.`Address` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Clients_Clients1`
    FOREIGN KEY (`Clients_id_recomanat_per`)
    REFERENCES `barcelona_activa`.`Clients` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barcelona_activa`.`Empleats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barcelona_activa`.`Empleats` (
  `num_empleat_id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  `cognoms` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`num_empleat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barcelona_activa`.`RegistreVenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barcelona_activa`.`RegistreVenda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Empleats_num_empleat_id` INT NOT NULL,
  `Clients_id` INT NOT NULL,
  `Ulleres_codi_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_RegistreVenda_Empleats1_idx` (`Empleats_num_empleat_id` ASC),
  INDEX `fk_RegistreVenda_Clients1_idx` (`Clients_id` ASC),
  INDEX `fk_RegistreVenda_Ulleres1_idx` (`Ulleres_codi_id` ASC),
  UNIQUE INDEX `Ulleres_codi_id_UNIQUE` (`Ulleres_codi_id` ASC),
  CONSTRAINT `fk_RegistreVenda_Empleats1`
    FOREIGN KEY (`Empleats_num_empleat_id`)
    REFERENCES `barcelona_activa`.`Empleats` (`num_empleat_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_RegistreVenda_Clients1`
    FOREIGN KEY (`Clients_id`)
    REFERENCES `barcelona_activa`.`Clients` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_RegistreVenda_Ulleres1`
    FOREIGN KEY (`Ulleres_codi_id`)
    REFERENCES `barcelona_activa`.`Ulleres` (`codi_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
